sidebar:
  Tutorial:
    - Get Started: docsforge-website/docs/get-started.md
    - Fundamentals: docsforge-website/docs/fundamentals.md
    - Advanced: docsforge-website/docs/advanced.md
    - Best Practices: docsforge-website/docs/best-practices.md
    - License: LICENSE
  
  Important API:
    - config_class: api/anyfig/anyfig_setup/config_class
    - init_config: api/anyfig/anyfig_setup/init_config
    - get_config: api/anyfig/figutils/get_config

autodocSettings:
  Public API:
    language: python
    INPUT: anyfig
    EXCLUDE: test tests examples setup.py test.py tests.py anyfig/dummyfields.py
    EXCLUDE_PATTERNS: '*/tests/* */test/*'
    includeApi: []
    excludeApi:
      - anyfig/dummyfields
    documentSingleUnderscore: false
    documentStatic: true
    documentProtected: true
    extractNonDocComments: false
    extract_namespace_comments: true
    sort_by_type: true
    sort_alphabetically: true
    separate_defines: false
    star_mentioned: true
    star_list: []
    ALIASES: ''
    EXAMPLE_PATH: ''

source_browser:
  title: 'Source Browser'
  base_url: 'source'
  input: 'anyfig'
  exclude: 'include/private'
  filename_extensions: '.py .pyw'

additionalSettings:
  markdown_fenced_code_tabs: true
